//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoEditorProto.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edoEntities : DbContext
    {
        public edoEntities()
            : base("name=edoEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudioCodec> AudioCodecs { get; set; }
        public virtual DbSet<Effect> Effects { get; set; }
        public virtual DbSet<Layer> Layers { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Row> Rows { get; set; }
        public virtual DbSet<RowEffect> RowEffects { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersEffect> UsersEffects { get; set; }
        public virtual DbSet<VideoCodec> VideoCodecs { get; set; }
    }
}
