//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoEditorProto.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Layer()
        {
            this.Rows = new HashSet<Row>();
        }
    
        public string Id { get; set; }
        public string IdProject { get; set; }
        public Nullable<byte> Muted_Showed { get; set; }
        public byte[] Blocked { get; set; }
        public long VersionNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Row> Rows { get; set; }
        public virtual Project Project { get; set; }
    }
}
