//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoEditorProto.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Row
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Row()
        {
            this.RowEffects = new HashSet<RowEffect>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdLayer { get; set; }
        public string MaterialFile { get; set; }
    
        public virtual Layer Layer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowEffect> RowEffects { get; set; }
    }
}
