//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoEditorProto.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersEffect
    {
        public string Id { get; set; }
        public string IdUser { get; set; }
        public string IdEffect { get; set; }
        public long VersionNum { get; set; }
    
        public virtual Effect Effect { get; set; }
        public virtual User User { get; set; }
    }
}
